apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curriculum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Greboh/Curriculum.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true