apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 16.7.26
      helm:
        valueFiles:
          - $values/apps/platform/postgresql/values.yaml
    - repoURL: https://github.com/opsdash/infrastructure.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true